### ISSUE TITLE
Design Recipe Assessments not generating PDF versions

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#401]
When building the algebra curriculum, exercises involving design recipes are generating the HTML files correctly, but those aren't being converted into the PDFs that the Unit links expect. See the tags with `make-exercise-locator/file`

**Comment by schanzer** [comment]
@ds26gte - tagging you here because this should be considered a serious, high-priority bug. Can you look into this as soon as possible?

**Comment by kfisler** [comment]
Sorry, which branch is this in?

**Comment by ds26gte** [comment]
@schanzer, could you check if this wasn't already fixed by a5bef3e (dated Aug 9), which should be included in the current `new-master`?

**Comment by schanzer** [comment]
Still not fixed. Take a look at the "check the design recipe" links at the bottom of `distribution/courses/algebra/en-us/units/unit4/index.html`

**Comment by schanzer** [comment]
Fixed. Thanks, @ds26gte !
